### ISSUE TITLE
Provide transpilled version in dist dir

### ISSUE THREAD

**Issue by qisoft** [RoviSys/signal-arr#10]
It would be nice if you will have already transpilled via babel version of lib. Now your code is not working with latest Babel (6.1.21) and I can't use it. Someone doesn't use es6 in their project, so they need to install Babel only for transpilling signal-arr. So es5 version would be a great solution to them.

**Comment by brandonalanskas** [comment]
We are currently working on an NPM release which will include ES5 code.
